"""Files the API keeps: uploaded datasets, generated PDFs, promoted populations.

``S3_BUCKET`` selects S3-compatible object storage (AWS S3, Cloudflare R2, MinIO,
...), configured by ``S3_ENDPOINT_URL`` (omit for AWS), ``S3_REGION``,
``S3_PREFIX`` and the usual ``AWS_ACCESS_KEY_ID`` / ``AWS_SECRET_ACCESS_KEY``.
Without it, files go to ``blobs/`` in the state directory, which is lost when a
container without a disk restarts.

Keys look like ``uploads/<id>.csv``; they are generated by the API, never taken
from a request.
"""

from __future__ import annotations

import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Protocol

from .config import get_paths
from .errors import NotFoundError

_KEY = re.compile(r"(uploads|reports)/[A-Za-z0-9_-]{1,64}\.(csv|pdf)")


def _check(key: str) -> str:
    if not _KEY.fullmatch(key):
        raise ValueError(f"Invalid blob key {key!r}")
    return key


class BlobStore(Protocol):
    kind: str

    def put(self, key: str, data: bytes, content_type: str) -> None: ...

    def get(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...


class LocalBlobStore:
    kind = "local"

    def __init__(self, root: Path):
        self.root = Path(root)

    def _path(self, key: str) -> Path:
        return self.root / _check(key)

    def put(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_bytes(data)
        tmp.replace(path)

    def get(self, key: str) -> bytes:
        path = self._path(key)
        if not path.is_file():
            raise NotFoundError(f"Stored file missing: {key}")
        return path.read_bytes()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


class S3BlobStore:
    kind = "s3"

    def __init__(self, bucket: str, prefix: str = "", endpoint_url: str | None = None, region: str | None = None):
        import boto3

        self.bucket, self.prefix = bucket, prefix.strip("/")
        self.client = boto3.client("s3", endpoint_url=endpoint_url or None, region_name=region or None)

    def _key(self, key: str) -> str:
        return f"{self.prefix}/{_check(key)}" if self.prefix else _check(key)

    def put(self, key: str, data: bytes, content_type: str) -> None:
        self.client.put_object(Bucket=self.bucket, Key=self._key(key), Body=data, ContentType=content_type)

    def get(self, key: str) -> bytes:
        try:
            return self.client.get_object(Bucket=self.bucket, Key=self._key(key))["Body"].read()
        except self.client.exceptions.NoSuchKey as exc:
            raise NotFoundError(f"Stored file missing: {key}") from exc

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=self._key(key))


@lru_cache(maxsize=1)
def get_blobstore() -> BlobStore:
    bucket = os.getenv("S3_BUCKET", "").strip()
    if bucket:
        return S3BlobStore(bucket, os.getenv("S3_PREFIX", ""), os.getenv("S3_ENDPOINT_URL"), os.getenv("S3_REGION"))
    return LocalBlobStore(get_paths()["state"] / "blobs")
