/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        ground: "#F3F2EE",
        surface: "#FFFFFF",
        "surface-alt": "#F6F5F1",
        tint: "#F1EFEA",
        line: "#E4E2DC",
        "line-soft": "#EEECE6",
        ink: "#14161B",
        "ink-2": "#4F5561",
        "ink-3": "#6B7280",
        night: "#101317",
        "night-2": "#1E232B",
        "night-line": "#262C35",
        "night-text": "#C9CDD4",
        "night-muted": "#8A919C",
        cobalt: "#2346C8",
        "cobalt-ink": "#1A3496",
        "cobalt-bg": "#E8EDFB",
        "cobalt-soft": "#EEF2FD",
        risk: "#B93C15",
        "risk-ink": "#7A2A10",
        "risk-text": "#9C3211",
        "risk-bg": "#FBE7DF",
        amber: "#E0873A",
        "amber-ink": "#7A4A06",
        "amber-bg": "#FBF1DE",
        neutral: "#C4C9D2",
      },
      fontFamily: {
        display: ["Fraunces", "Georgia", "serif"],
        sans: ["'IBM Plex Sans'", "system-ui", "sans-serif"],
        mono: ["'IBM Plex Mono'", "ui-monospace", "monospace"],
      },
      borderRadius: {
        md: "8px",
        lg: "10px",
        xl: "14px",
      },
      keyframes: {
        "fade-up": { from: { opacity: "0", transform: "translateY(6px)" }, to: { opacity: "1", transform: "none" } },
        pulse: { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.35" } },
      },
      animation: {
        "fade-up": "fade-up 240ms ease-out both",
        pulse: "pulse 1.2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
