"""
Data quality assessment of the SGCC dataset (proposal Appendix A.1).

    python scripts/data_quality.py

Fills the proposal's checklist from the data itself: integrity, completeness,
quality, class distribution, outliers, and the preprocessing log of the
section 3.7 cleaning. Writes artifacts/data_quality.json and
docs/data-quality.md (the Appendix A tables, ready to paste).
"""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.data_loader import load_wide  # noqa: E402
from src.preprocessing import DEFAULT_CLEANING_CONFIG, clean_series  # noqa: E402
from src.train import load_config  # noqa: E402

EXPECTED = {"customers": 42_372, "theft": 3_615, "honest": 38_757, "start": "2014-01-01", "end": "2016-10-31"}


def longest_runs(mask: np.ndarray) -> np.ndarray:
    """Longest run of True in each row."""
    padded = np.zeros((mask.shape[0], mask.shape[1] + 2), dtype=np.int8)
    padded[:, 1:-1] = mask
    edges = np.diff(padded, axis=1)
    rows, starts = np.nonzero(edges == 1)
    _, ends = np.nonzero(edges == -1)
    longest = np.zeros(mask.shape[0], dtype=int)
    np.maximum.at(longest, rows, ends - starts)
    return longest


def assess(path: Path, cleaning: dict) -> dict:
    raw = pd.read_csv(path, low_memory=False)
    wide, labels = load_wide(str(path))
    W = wide.to_numpy(dtype=float)
    y = labels.reindex(wide.index).to_numpy().astype(int)
    missing = np.isnan(W)
    calendar = pd.date_range(EXPECTED["start"], EXPECTED["end"], freq="D")
    absent_dates = [d.strftime("%Y-%m-%d") for d in calendar.difference(wide.columns)]
    with np.errstate(invalid="ignore"):
        mean = np.nanmean(np.where(missing.all(axis=1, keepdims=True), 0.0, W), axis=1, keepdims=True)
        std = np.nanstd(np.where(missing.all(axis=1, keepdims=True), 0.0, W), axis=1, keepdims=True)
        sigma_outliers = int(((np.abs(W - mean) > 3 * std) & (std > 0)).sum())
    zero_runs = longest_runs(W == 0)
    missing_share = missing.mean(axis=1)
    _, cleaning_log = clean_series(wide, cleaning)

    return {
        "integrity": {
            "file": path.name,
            "file_size_mb": round(path.stat().st_size / 1e6, 1),
            "layout": f"wide: one row per customer, CONS_NO + FLAG + {wide.shape[1]:,} date columns",
            "rows_in_file": int(len(raw)),
            "duplicate_customer_rows": int(raw.duplicated(subset="CONS_NO").sum()),
            "customers": int(len(wide)),
            "days": int(wide.shape[1]),
            "calendar_days_in_range": int(len(calendar)),
            "absent_dates": absent_dates,
            "first_date": wide.columns[0].strftime("%Y-%m-%d"),
            "last_date": wide.columns[-1].strftime("%Y-%m-%d"),
            "cells": int(W.size),
        },
        "completeness": {
            "missing_cells": int(missing.sum()),
            "missing_percent": round(float(missing.mean() * 100), 2),
            "customers_complete": int((~missing.any(axis=1)).sum()),
            "customers_without_readings": int(missing.all(axis=1).sum()),
            "customers_over_10pct_missing": int((missing_share > 0.10).sum()),
            "theft_customers_over_10pct_missing": int(((missing_share > 0.10) & (y == 1)).sum()),
            "missing_percent_honest": round(float(missing[y == 0].mean() * 100), 2),
            "missing_percent_theft": round(float(missing[y == 1].mean() * 100), 2),
            "labels_missing": int(raw["FLAG"].isna().sum()),
        },
        "quality": {
            "negative_readings": int((W < 0).sum()),
            "readings_above_10000_kwh": int((W > 10_000).sum()),
            "readings_above_15000_kwh": int((W > 15_000).sum()),
            "max_reading_kwh": float(np.nanmax(W)),
            "median_reading_kwh": float(np.nanmedian(W)),
        },
        "class_distribution": {
            "honest": int((y == 0).sum()),
            "theft": int((y == 1).sum()),
            "theft_percent": round(float(y.mean() * 100), 2),
            "imbalance_ratio": round(float((y == 0).sum() / (y == 1).sum()), 2),
            "expected": EXPECTED,
        },
        "outliers": {
            "negative": int((W < 0).sum()),
            "above_10000_kwh": int((W > 10_000).sum()),
            "customers_with_zero_runs_over_30_days": int((zero_runs > 30).sum()),
            "cells_beyond_3_sd": sigma_outliers,
        },
        "preprocessing_log": cleaning_log,
    }


def markdown(r: dict) -> str:
    i, c, q, d, o, p = (r[k] for k in ("integrity", "completeness", "quality", "class_distribution", "outliers", "preprocessing_log"))
    pct = lambda n, total: f"{n / total * 100:.2f}%"  # noqa: E731
    rows = [
        "# SGCC data quality assessment (proposal Appendix A.1)",
        "",
        "Generated by `python scripts/data_quality.py` from the dataset itself.",
        "",
        "## I. Dataset integrity check",
        "",
        "| Verification item | Expected (proposal) | Actual | Status | Notes |",
        "|---|---|---|---|---|",
        f"| Total number of customers | 42,372 | {i['customers']:,} | {'✓' if i['customers'] == 42_372 else '✗'} | {i['duplicate_customer_rows']} duplicated customer rows in the file |",
        f"| Total number of days | 1,035 | {i['days']:,} | ✗ | The range spans {i['calendar_days_in_range']:,} calendar days; absent: {', '.join(i['absent_dates']) or 'none'} |",
        f"| Date range | 1 Jan 2014 – 31 Oct 2016 | {i['first_date']} – {i['last_date']} | ✓ | |",
        f"| Total records | ~43,850,520 | {i['cells']:,} customer-days | ✗ | {i['customers']:,} × {i['days']:,} |",
        f"| File format | CSV | CSV, {i['layout']} | ✓ | |",
        f"| File size | ~450 MB compressed | {i['file_size_mb']} MB uncompressed | ✗ | |",
        f"| Columns present | 4 (ID, Date, Consumption, Label) | {i['days'] + 2:,} | ✗ | Wide layout, not long |",
        "",
        "## II. Data completeness assessment",
        "",
        "| Completeness metric | Threshold | Actual | Pass/Fail | Action |",
        "|---|---|---|---|---|",
        f"| Missing values | < 0.1% | {c['missing_percent']}% ({c['missing_cells']:,} cells) | Fail | Keep as signal; impute only for methods that need complete rows |",
        f"| Customers with complete records | > 99% | {c['customers_complete']:,} ({pct(c['customers_complete'], i['customers'])}) | Fail | As above |",
        f"| Temporal continuity | All 1,035 days | {i['days']:,} days | Fail | {', '.join(i['absent_dates']) or '-'} absent from the release |",
        f"| Label completeness | 100% | {pct(i['customers'] - c['labels_missing'], i['customers'])} | Pass | |",
        f"| Missing, honest vs theft | - | {c['missing_percent_honest']}% vs {c['missing_percent_theft']}% | - | Missingness differs by class: it is theft signal |",
        f"| Customers > 10% missing (proposal's exclusion rule) | - | {c['customers_over_10pct_missing']:,} customers, {c['theft_customers_over_10pct_missing']:,} of {d['theft']:,} thefts | - | Rule not applied: it would remove most thefts |",
        "",
        "## III. Data quality metrics",
        "",
        "| Quality dimension | Assessment method | Finding |",
        "|---|---|---|",
        f"| Accuracy | Negative/impossible values | {q['negative_readings']:,} negative readings |",
        f"| Validity | Range 0–15,000 kWh | {q['readings_above_15000_kwh']:,} readings above 15,000 kWh; {q['readings_above_10000_kwh']:,} above 10,000 kWh; maximum {q['max_reading_kwh']:,.0f} kWh |",
        f"| Uniqueness | Duplicate customers | {i['duplicate_customer_rows']:,} duplicated rows |",
        "| Timeliness | Date sequence | Dates stored out of order in the header (e.g. 2014/1/1, 2014/1/10); sorted chronologically on load |",
        "",
        "## IV. Class distribution verification",
        "",
        "| Class | Expected count | Expected % | Actual count | Actual % |",
        "|---|---|---|---|---|",
        f"| Honest (0) | 38,757 | 91.5% | {d['honest']:,} | {100 - d['theft_percent']:.2f}% |",
        f"| Theft (1) | 3,615 | 8.5% | {d['theft']:,} | {d['theft_percent']:.2f}% |",
        f"| Imbalance ratio | 10.72 : 1 | | {d['imbalance_ratio']} : 1 | |",
        "",
        "## V. Outlier detection summary",
        "",
        "| Outlier type | Detection method | Count | Treatment applied |",
        "|---|---|---|---|",
        f"| Negative consumption | Value < 0 | {o['negative']:,} | Replace with customer median |",
        f"| Extremely high | Value > 10,000 kWh | {o['above_10000_kwh']:,} | Capped at 10,000 kWh |",
        f"| Zero-consumption clusters | Consecutive zeros > 30 days | {o['customers_with_zero_runs_over_30_days']:,} customers | Flagged, kept (possible tampering) |",
        f"| Statistical outliers | Mean ± 3 SD per customer | {o['cells_beyond_3_sd']:,} readings | Replace with customer median |",
        "",
        "## VI. Preprocessing log (section 3.7 cleaning)",
        "",
        "| Action | Records affected |",
        "|---|---|",
        f"| Negative readings replaced | {p['negative_replaced']:,} |",
        f"| Readings capped at 10,000 kWh | {p['capped_above_limit']:,} |",
        f"| 3-SD outliers replaced by median | {p['outliers_replaced']:,} |",
        f"| Gaps ≤ 3 days linearly interpolated | {p['short_gap_cells_interpolated']:,} cells |",
        f"| Longer gaps forward/back-filled | {p['long_gap_cells_filled']:,} cells |",
        f"| Customers without any reading (set to 0) | {p['customers_without_readings']:,} |",
        "",
    ]
    return "\n".join(rows)


def main() -> None:
    config = load_config()
    path = ROOT / config["data"]["training_data_path"]
    report = assess(path, {**DEFAULT_CLEANING_CONFIG, **config.get("preprocessing", {})})
    (ROOT / "artifacts" / "data_quality.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    (ROOT / "docs" / "data-quality.md").write_text(markdown(report), encoding="utf-8")
    print(json.dumps({k: report[k] for k in ("completeness", "class_distribution", "outliers")}, indent=2))


if __name__ == "__main__":
    main()
